/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class termui_console_Console */

#ifndef _Included_termui_console_Console
#define _Included_termui_console_Console
#ifdef __cplusplus
extern "C" {
#endif
#undef termui_console_Console_DEFAULT_CLEAR_UNIT
#define termui_console_Console_DEFAULT_CLEAR_UNIT 32L
/*
 * Class:     termui_console_Console
 * Method:    setColorPair
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_termui_console_Console_setColorPair
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    getScreenWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_termui_console_Console_getScreenWidth
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    getScreenHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_termui_console_Console_getScreenHeight
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    readBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_termui_console_Console_readBytes
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    blockingReadBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_termui_console_Console_blockingReadBytes
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    drawChar
 * Signature: (IICII)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_drawChar
  (JNIEnv *, jclass, jint, jint, jchar, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    drawBorder
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_drawBorder__IIIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    drawBorder
 * Signature: (IIIIIICCCCCC)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_drawBorder__IIIIIICCCCCC
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jchar, jchar, jchar, jchar, jchar, jchar);

/*
 * Class:     termui_console_Console
 * Method:    drawBorderMinMax
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_drawBorderMinMax
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    drawString
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_drawString
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    clearArea
 * Signature: (IIIICII)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_clearArea
  (JNIEnv *, jclass, jint, jint, jint, jint, jchar, jint, jint);

/*
 * Class:     termui_console_Console
 * Method:    startDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_startDraw
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    endDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_endDraw
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    clearLine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_clearLine
  (JNIEnv *, jclass, jint);

/*
 * Class:     termui_console_Console
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_clearScreen
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_init
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     termui_console_Console
 * Method:    refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_termui_console_Console_refresh
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
